version: '3'

services:
  store:
    image: rg.fr-par.scw.cloud/prelab/modelyz
    command: /srv/store/store -h store
    ports:
      - "8081:8081"
    volumes:
      - store:/srv/store/data

  studio:
    image: rg.fr-par.scw.cloud/prelab/modelyz
    command: /srv/studio/studio -d studio -f studio/data/messagestore.txt --store_host store
    environment:
      - WSS=ws://localhost:8080
    depends_on:
      - store
    ports:
      - "8080:8080"
    volumes:
      - studio:/srv/studio/data

  ident:
    image: rg.fr-par.scw.cloud/prelab/modelyz
    command: /srv/ident/ident --store_host store
    depends_on:
      - store
    volumes:
      - ident:/srv/ident/data

volumes:
  store:
  studio:
  ident:
